# -------------------- 应用级 --------------------
server:
  port: 27900

spring:
  application:
    name: big_boot  # 指定应用名
  profiles:
    active: dev  # 指定激活文件
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决Springboot与Swagger路径匹配策略冲突

mybatis-plus:
  global-config:
    banner: off  # 指定mybatis-plus的封面不显示
  configuration:
    call-setters-on-nulls: true  # 指定resultType的类型为java.util.map发现字段为null时其Key仍保留

logging:
  config: classpath:logback-spring.xml  # 指定日志陪着文件
  file:
    path: logs  # 指定日志基础目录

docs:
  title: big_boot-default  # 文档标题
  description: Springboot大操场，集成一些基于Springboot的实验  # 文档描述

# -------------------- stock --------------------
stock:
  market:
    sh: 600, 601, 603, 605, 688  # 沪市股票代码前缀
    sz: 000, 001, 003, 300, 301, 002  # 深市股票代码前缀
    etfSh: 51, 56, 58  # 沪市股票ETF代码前缀
    etfSz: 159  # 深市股票ETF代码前
