server:
  port: 18999

spring:
  application:
    name: big_boot  # 指定应用名
  profiles:
    active: dev  # 指定激活文件
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决Springboot与Swagger路径匹配策略冲突

mybatis-plus:
  global-config:
    banner: off  # 指定mybatis-plus的封面不显示
  configuration:
    call-setters-on-nulls: true  # 指定resultType的类型为java.util.map发现字段为null时其Key仍保留

logging:
  config: classpath:logback-spring.xml
  file:
    path: logs

stock:
  market:
    sh: 600, 601, 603, 605, 688
    sz: 000, 001, 003, 300, 301, 002
