# -------------------- 应用级 --------------------
spring:
  datasource:
    url: jdbc:sqlite:///Users/zhongshijie/Desktop/01-Project/big_boot/big_boot-dev.db

docs:
  title: big_boot-dev
  description: Springboot大操场，集成一些基于Springboot的实验

# -------------------- stock --------------------
